import "@repo/ui/styles.css";
import "./global.css";

import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { MswProvider } from "./MswProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "mniii arc turbo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html className="dark" lang="en">
      <body className={inter.className}>
        <MswProvider>{children}</MswProvider>
      </body>
    </html>
  );
}
